### ISSUE TITLE
Add automatic "pull" of notes

### ISSUE THREAD

**Issue by gamberoillecito** [deptyped/notepher-bot#38]
Hi, I really enjoy using your app but I find it annoying when I switch from one device to another that I always have to click the cloud icon to receive the edits I made on the other device.

Would it be possible to automatically refresh the notes every couple of seconds to avoid this issue?

**Comment by deptyped** [comment]
Thanks for the idea. I added the ability to enable auto-sync in the settings.

![image](https://github.com/deptyped/notepher-bot/assets/26162440/f0bfa6e6-6bf9-4a7d-ab1a-4fcf5b52f122)

**Comment by gamberoillecito** [comment]
Wow that was fast. Thank you so much
